name: test_all_units
on:
  push:
    branches:
      - branch1
    tags:
      - '*'
  pull_request:
    branches:
      - branch1

jobs:
  Q1:                       # job 1: build and test the code; you can have additional jobs to upload/deploy
    name: Build/test Q1    # name of job 1
    strategy:
      matrix:                     # build and test on 4 OSes provided by github
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    defaults:                     # forcing each OS to use bash as default
      run:
        shell: bash
    steps:                        # each job is made of steps
      - name: Checkout repo       # each step has a name, and a bunch of commands
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies (Linux only)
        if: ${{ runner.os == 'Linux' }}   # use these variables to limit a step only on a specific OS
        run: |
          sudo apt-get update && sudo apt-get install -y gcc
      - name: Build program (debug mode) # build software
        run: |
          cd HW3/Q1
          make clean
          #make all    ## uncomment this line also works if the windows-only step for CC setting is added
          if [ "$RUNNER_OS" == "Windows" ]; then  # you can also use shell env variable to test OS/version in the run-script
            make all CC=gcc
          else
            make all
          fi
      - name: Test program (non Windows) # run tests
        if: ${{ runner.os != 'Windows' }}
        run: |
          cd HW3/Q1
          make test
      - name: Build program in release mode   # you can rebuild the programs in other options, or compilers and further test
        run: |
          cd HW3/Q1
          make clean
          if [ "$RUNNER_OS" == "Windows" ]; then
            make release CC=gcc
          else
            make release
          fi

