name: test_all_units
on:
  push:
    branches:
      - branch1
    tags:
      - '*'
  pull_request:
    branches:
      - branch1

jobs:
  Q1:                       
    name: Build/test Q1    
    strategy:
      matrix:                     
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    defaults:                 
      run:
        shell: bash
    steps:                       
      - name: Checkout repo       
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies (Linux only)
        if: ${{ runner.os == 'Linux' }}   # use these variables to limit a step only on a specific OS
        run: |
          sudo apt-get update && sudo apt-get install -y gcc
      - name: Build/Test
        run: |
          cd HW3/Q1
          make test
  Q2: 
    name: Build/test Q2   
    strategy:
      matrix:                     
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    defaults:                 
      run:
        shell: bash
    steps:                       
      - name: Checkout repo       
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies (Linux only)
        if: ${{ runner.os == 'Linux' }}   # use these variables to limit a step only on a specific OS
        run: |
          sudo apt-get update && sudo apt-get install -y gcc
      - name: Build/Test
        run: |
          cd HW3/Q2
          make test
  Q3: 
    name: Build/test Q3   
    strategy:
      matrix:                     
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    defaults:                 
      run:
        shell: bash
    steps:                       
      - name: Checkout repo       
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies (Linux only)
        if: ${{ runner.os == 'Linux' }}   # use these variables to limit a step only on a specific OS
        run: |
          sudo apt-get update && sudo apt-get install -y gcc
      - name: Build/Test
        run: |
          cd HW3/Q3
          make test
  Q4: 
    name: Build/test Q4  
    strategy:
      matrix:                     
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    defaults:                 
      run:
        shell: bash
    steps:                       
      - name: Checkout repo       
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies (Linux only)
        if: ${{ runner.os == 'Linux' }}   # use these variables to limit a step only on a specific OS
        run: |
          sudo apt-get update && sudo apt-get install -y gcc
      - name: Build/Test
        run: |
          cd HW3/Q4
          make laplace 
          make run
